<?php

namespace Proxies\__CG__\LibraryBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Etat extends \LibraryBundle\Entity\Etat implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'LibraryBundle\\Entity\\Etat' . "\0" . 'id', '' . "\0" . 'LibraryBundle\\Entity\\Etat' . "\0" . 'neuf', '' . "\0" . 'LibraryBundle\\Entity\\Etat' . "\0" . 'occasion', '' . "\0" . 'LibraryBundle\\Entity\\Etat' . "\0" . 'detruit', '' . "\0" . 'LibraryBundle\\Entity\\Etat' . "\0" . 'pageDechire'];
        }

        return ['__isInitialized__', '' . "\0" . 'LibraryBundle\\Entity\\Etat' . "\0" . 'id', '' . "\0" . 'LibraryBundle\\Entity\\Etat' . "\0" . 'neuf', '' . "\0" . 'LibraryBundle\\Entity\\Etat' . "\0" . 'occasion', '' . "\0" . 'LibraryBundle\\Entity\\Etat' . "\0" . 'detruit', '' . "\0" . 'LibraryBundle\\Entity\\Etat' . "\0" . 'pageDechire'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Etat $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setNeuf($neuf)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNeuf', [$neuf]);

        return parent::setNeuf($neuf);
    }

    /**
     * {@inheritDoc}
     */
    public function getNeuf()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNeuf', []);

        return parent::getNeuf();
    }

    /**
     * {@inheritDoc}
     */
    public function setOccasion($occasion)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setOccasion', [$occasion]);

        return parent::setOccasion($occasion);
    }

    /**
     * {@inheritDoc}
     */
    public function getOccasion()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOccasion', []);

        return parent::getOccasion();
    }

    /**
     * {@inheritDoc}
     */
    public function setDetruit($detruit)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDetruit', [$detruit]);

        return parent::setDetruit($detruit);
    }

    /**
     * {@inheritDoc}
     */
    public function getDetruit()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDetruit', []);

        return parent::getDetruit();
    }

    /**
     * {@inheritDoc}
     */
    public function setPageDechire($pageDechire)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPageDechire', [$pageDechire]);

        return parent::setPageDechire($pageDechire);
    }

    /**
     * {@inheritDoc}
     */
    public function getPageDechire()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPageDechire', []);

        return parent::getPageDechire();
    }

}
